feat(ecs): add open telemetry sidecar construct
capralifecycle/liflig-cdk pull request #140
Opened 2022-07-07 13:12 UTC by krissrex

This will create a sidecar on a FargateService construct,
which collects open telemetry-data from the service's instrumentation
agent.
The data is forwarded to CloudWatch Metrics and XRay.

More documentation of the full setup can be found in EP's confluence space: https://confluence.capraconsulting.no/x/R7rWCQ

2025-01-08 12:26 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +    const sidecarVersion = this.props?.dockerImageVersion ?? "0.21.0" // FIXME let renovate detect this
"0.21.0" må kanskje oppdateres

2025-01-08 12:28 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +const awsOtelCustomConfigYaml = `extensions:
Tror jeg har splittet denne til egen fil i DTP

2025-01-08 12:39 UTC, krissrex commented
TODO:

- [ ] Rebase på master
- [ ] Skriv om til ESM?
- [ ] Oppdater versjonsnummer til sidecar
- [ ] Splitt config til egen fil?

2025-07-28 13:29 UTC, krissrex commented
In case an official L3 construct is added, this is their issue https://github.com/aws/aws-cdk/issues/24630 .

2025-07-31 08:45 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +  path.resolve(
Jeg håper ikke readFile skaper problemer når man bruker cdk? Lignende brukes jo av lambdas for kode.

2025-07-31 08:53 UTC, joakimen requested changes
Super innsats! Lagt ved noen kommentarer/ønsker, hovedsakelig med lesbarhet/vedlikeholdbarhet i tankene.

### Feedback

#### Oppsummering av PR
Kan vi få en executive summary i PR-description?
- **Vedlikehold**
  - Hvordan verifiserer vi featuren, er det noe utover instansiering av construct i tests som bør utføres for å forsikre at oppsett fungerer som tiltenkt?
  - Hvordan verifiserer vi konfigurasjonsfil i fremtiden hvis vi henter en ny versjon og fletter inn våre Liflig-spesifikke endringer?
- **Målgruppe**: Hvilke teams bruker i dag custom OTEL sidecar-implementasjoner, og vil ha nytte av denne featuren?
- **Impact**: Påvirker endringen eksisterende konsumenter av bibliotek? (Svaret her er vel nei, men greit å ha i oppsummering)
- **Renovate:** Siden det er en custom Renovate-konfigurasjon hadde det vært fint med et par ord om løsningen
  
#### Kodefeedback

Ikke noe å utsette på kode, annet enn noen små dokumentasjonsrettede justeringer. Har lagt ved en del små nitpick-suggestions for å korrigere `java` til `Java` o.l. i GitHub UI fordi det var praktisk, men gjør gjerne endringene selv utenfor GitHub UI hvis du ikke vil at jeg skal stå som co-author på PR, hipp som happ for meg

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +     * - tcp 55681 : OpenTelemetry collection HTTP
Vil utviklerne forholde seg til disse portene i konfing av tjenestene sine, eller er dette detaljer som blir abstrahert bort? Hvis ikke så kan vi sikkert droppe å liste de i kommentar, og heller ha en link til dokumentasjon hvor de og resterende porter er dokumentert, så slipper vi at det blir utdatert den dagen `aws-otel-collector` endrer implementasjonsdetaljer

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +   * You also need to add either the Java SDK for OTel or a java agent,
```suggestion
   * You also need to add either the Java SDK for OTel or a Java agent,
```

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +   * The open-telemetry java agent may run by default in the Docker image.
```suggestion
   * The open-telemetry Java agent may run by default in the Docker image.
```

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> + * An example of a java auto-instrumentation agent in docker can be found
```suggestion
 * An example of a Java auto-instrumentation agent in Docker can be found
```

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +   * The open-telemetry java agent may run by default in the Docker image.
```suggestion
   * The OpenTelemetry Java agent may run by default in the Docker image.
```

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> + * You also need to add either the Java SDK for OTel or a java agent,
```suggestion
 * You also need to add either the Java SDK for OTel or a Java agent,
```

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +   * This is the yaml config for the open-telemetry collector sidecar.
```suggestion
   * This is the YAML config for the OpenTelemetry collector sidecar.
```

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> + * You can also disable the Open Telemetry instrumentation agent
```suggestion
 * You can also disable the OpenTelemetry instrumentation agent
```

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +class OpenTelemetryPolicies extends constructs.Construct {
Skulle hatt en høynivå docstring som beskriver hensikt/ansvar med klassen

2025-07-31 08:53 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +  public static disableOpenTelemetryJavaAgent(service: FargateService) {
Trenger vi både denne og `public disableOpenTelemetryJavaAgent()` som adskilte metoder?

Hvis ja
- bør static-metoden være `private`, hvis den alltid kalles av `disableOpenTelemetryJavaAgent()`?
- kan vi oppdatere docstrings til å tydeliggjøre hvorfor vi trenger begge?

2025-07-31 08:53 UTC, joakimen commented on src/ecs/__tests__/fargate-service.test.ts
> +
Kanskje også ha noe kode som exerciser funksjonalitet for disabling av agent?

2025-07-31 09:03 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +const awsOtelCustomConfigYaml = readFileSync(
Den evalueres nå 1 gang totalt ved import (module singleton). Hvis den er en metode evalueres den hver eneste gang det brukes.

Hvis man importer denne filen, så skal man høyst sannsynlig bruke denne verdien.
99,999% av use-caser kommer ikke til å sette awsOtelConfig. Så resten kommer til å lese filen hver gang.

2025-07-31 09:06 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +     * - tcp 55681 : OpenTelemetry collection HTTP
Det er en standard og brukes for vår referanse. Vi binder opp disse rett under, til env vars på containeren.

Hvorfor slå opp docs for å vite hva 
```
"OTEL_EXPORTER_OTLP_ENDPOINT",
      "http://localhost:4317",
``` 
er, i stedet for å bare si at det er GRPC endpointet?

2025-07-31 09:10 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +class OpenTelemetryPolicies extends constructs.Construct {
Selv når den ikke er exportet?

2025-07-31 09:16 UTC, krissrex commented on src/ecs/__tests__/fargate-service.test.ts
> +
Den er ikke noe gøy, den bare setter en env variabel. Men det er mulig

2025-07-31 10:18 UTC, krissrex commented on renovate.json5
> +      "depNameTemplate": "amazon/aws-otel-collector",
Det er vanskelig å vite om denne er riktig før man er på master. Jeg vet ikke hvordan man får debugget renovate configs

2025-07-31 10:23 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +     * - tcp 55681 : OpenTelemetry collection HTTP
I tillegg så er det noe som kommer fra vår config, så hvis vi endrer det i config blir det kluss

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp
  awsecscontainermetrics:
```

2025-07-31 10:24 UTC, krissrex commented on src/ecs/open-telemetry.ts
> +     * - tcp 55681 : OpenTelemetry collection HTTP
Jeg kan legge inn en kommentar der det passer

2025-07-31 10:31 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +     * - tcp 55681 : OpenTelemetry collection HTTP
Det er det jeg mener;
- `OpenTelemetry collection GRPC` + `AWS XRay` ports refereres, så de er kjekt at ligger der
- `OpenTelemetry collection HTTP` refereres kun i config-filen
- `AWS CloudWatch EMF collection` refereres ikke i det hele tatt, så trenger kanskje ikke å ligge der som kommentar

2025-07-31 10:43 UTC, krissrex commented on src/ecs/__tests__/fargate-service.test.ts
> +
Flytta det til en egen test-fil, siden det krever mye støy å sette opp en service først.

2025-07-31 10:50 UTC, joakimen commented on assets/open-telemetry/otel-collector-task-metrics-config.yaml
> +## Validate using https://www.otelbin.io/#distro=adot%7E&distroVersion=v0.43.1%7E .
Ja, var innom siden, men er det alt? Regner med siden sier om koden er syntaktisk gyldig, men tenkte semantisk med vårt oppsett, om endringer i konfigurasjonsfilen vil kunne eksplodere et sted borti infrastrukturen. In short, at konfigurasjon og infrastruktur sammen er gyldig. Hvis ingenting i en gyldig konfigfil kan skape feil utover endret oppførsel så er det greit nok

2025-07-31 11:35 UTC, joakimen commented on src/ecs/open-telemetry.ts
> +  public static disableOpenTelemetryJavaAgent(service: FargateService) {
Enig i resonnementet, la stå

2025-07-31 11:43 UTC, krissrex commented on assets/open-telemetry/otel-collector-task-metrics-config.yaml
> +## Validate using https://www.otelbin.io/#distro=adot%7E&distroVersion=v0.43.1%7E .
Det er vanskelig å teste andre ting. 
Om du feks bytter grpc port, så vil jo collectoren slutte å få data når prosjektene til kunder fortsatt sender på den gamle porten.

Og litt farligere er hvis noen klusser med de som står markert under
```
      # Http adds lots of high cardinality, which xray creates 1 metric per. Expensive.
```

2025-07-31 11:50 UTC, joakimen commented on assets/open-telemetry/otel-collector-task-metrics-config.yaml
> +## Validate using https://www.otelbin.io/#distro=adot%7E&distroVersion=v0.43.1%7E .
Ok, så ingen verktøybasert validering/linting av dårlige/farlige konfigurasjoner. Regnet ikke med det var så lett tilgjengelig, men var verdt å høre! Da kjører vi med config as is, så får vi håpe at de som skrur på ting der inne har kontroll. 😁

2025-07-31 11:51 UTC, joakimen approved these changes
LGTM, squash/rebase som du ønsker

2025-07-31 12:25 UTC, merged