feat: alarms for ses and spf records as default
capralifecycle/liflig-cdk pull request #162
Opened 2022-12-05 11:56 UTC by evan-boone

2022-12-13 13:33 UTC, aleksil requested changes

2022-12-13 13:33 UTC, aleksil commented on src/ses/sesdomain/index.ts
>          // Bump this if changing logic in the lambda that should be
Kommentaren her ligger nå på feil felt

2022-12-13 13:33 UTC, aleksil commented on src/ses/sesdomain/index.ts
> +  spfRecordValues?: string[]
Dette git ikke mening. Man kan ikke ha flere SPF TXT-records for et gitt domene, og om disse blir konkatenert til en record så vil alt etter `-all` feile uansett (ref eksempelet du har i snapshots).

Jeg tror det gir mer mening å kun ta inn en enkelt string, siden vi uansett kun skal produsere en record.

2022-12-13 13:33 UTC, aleksil commented on src/ses/sesdomain/index.ts
> +  spfRecordValues?: string[]
Dette blir forøvrig en breaking change, siden vi i de fleste løsningene manuelt legger til SPF-records, så disse må fjernes samtidig som man bumper til ny versjon av liflig-cdk der dette legges til av oss.

2022-12-15 11:35 UTC, aleksil approved these changes
La til to nits, ellers ser det bra ut nå :+1:

2022-12-15 11:35 UTC, aleksil commented on src/ses/sesdomain/index.ts
> +   * @default ["v=spf1 include:amazonses.com ~all"]
Skal ikke lenger være en array her

2022-12-15 11:35 UTC, aleksil commented on src/ses/sesdomain/index.ts
> +  spfRecordValues?: string
Kan med fordel droppe flertall og endre til `spfRecordValue` her og andre steder

2022-12-20 12:44 UTC, stekern commented on src/alarms/ses-alarms.ts
> +      unit: Unit.PERCENT,
I'm not sure if this actually works as expected. As far as I know, this metric does not actually have any unit set for its datapoints. I think you may want to remove the unit altogether here, and update the threshold value accordingly

2022-12-20 12:44 UTC, stekern commented on src/alarms/ses-alarms.ts
> +      threshold: props?.complaintRateAlarm?.threshold ?? 0.07,
I think you'll need to divide the threshold value by 100. May also want to consider just making the threshold half of what it takes to get an account under review (e.g., `0.0005`)

2022-12-20 12:53 UTC, stekern commented on src/alarms/ses-alarms.ts
> +      unit: Unit.PERCENT,
I'm not sure if this actually works as expected. As far as I know, this metric does not actually have any unit set for its datapoints. I think you may want to remove the unit altogether here, and update the threshold value accordingly

2022-12-20 13:25 UTC, evan-boone commented on src/alarms/ses-alarms.ts
> +      period: cdk.Duration.days(1),
If the period is so short, won't an alarm most likely get sent almost every time a BOUNCE or COMPLAINT happens?

2023-01-02 12:58 UTC, stekern approved these changes
LGTM 🚀 

(You may want to do a rebase to squash the commits and get a cleaner commit history, or just a squash and merge through the GitHub UI)

2023-01-02 12:58 UTC, stekern commented on src/ses/configurationsetsnsdestination/index.ts
> +   * Whether SES events will be logged to SNS
nit: I think mentioning CloudWatch here would be more accurate and descriptive, as that is what this toggle effectively does. `Whether SES events should be logged to CloudWatch`?

2023-01-02 15:42 UTC, merged

2023-01-02 15:46 UTC, calsCI commented
:tada: This PR is included in version 2.9.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@liflig/cdk/v/2.9.0)
- [GitHub release](https://github.com/capralifecycle/liflig-cdk/releases/tag/v2.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: