feat: make cw rum construct
capralifecycle/liflig-cdk pull request #216
Opened 2023-10-20 08:17 UTC by jakob-lj

App monitor construct setting up infrastructure needed for Real User Monitoring from Webapp clients.

2023-10-23 11:55 UTC, evan-boone reviewed
Ser generelt veldig bra inn! Jeg la inn noen kommentarer, mest mindre kommentarer rundt defaults

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +  webappDomain: string
nit: Jeg hadde nok brukt webappDomainName

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +  telemetries: CwRumTelemetries
Kan det gi mening å sette en default her, eller tror du de fleste applikasjoner kommer til å ha ganske ulike behov?

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +   * cookie consent before enabling cookies in the AWS RUM SDK api on FE
nit: hadde skrevet frontend istedenfor FE

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +   * We highly recommend using the Unathenticated authentication here as there might be GDPR issues using CW RUM with the congito user pool
Hvis det kanskje ikke er innafor å bruke egen identity pool pga GDPR, ønsker vi egentlig å gi team mulighet til å gjøre det? Kanskje unauthenticated authentication bør settes opp for alle, uten mulighet til å overstyre her?

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +   * Note: we will add a policy to PutEvents by cognito-identity service principal for unathenticated users.
nit: Trenger denne linjen å være med i docs? Trenger man å tenke på eller forholde seg til denne policyen?

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +     * Attach policy here in stead of above as role is optional
Hva mener du her?

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +      : new cognito.CfnIdentityPool(this, "IdentityPool", {
Kanskje `RumIdentityPool` som ID?

2023-10-23 11:55 UTC, evan-boone commented on src/webapp/app-monitor.ts
> +  sampleRate?: number
Kanskje denne kan hete `sessionSampleRate` så det blir litt tydeligere? Og ønsker vi at default er at 100% av sesjoner blir sampled? Risikerer vi ikke at det kommer veldig mange eventer hvis det er en løsning med mye trafikk?

2023-10-23 13:26 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +  webappDomain: string
Nais, jeg endrer

2023-10-23 13:26 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +  telemetries: CwRumTelemetries
Tror alle ønsker å bruke det samme, men kanskje man burde ha et forhold til hva man setter opp? Jeg tror en konsument burde ha tenkt gjennom hvorfor man samler inn det man samler inn. 

Det samme må configures i webapp repo uansett

2023-10-23 13:28 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +   * We highly recommend using the Unathenticated authentication here as there might be GDPR issues using CW RUM with the congito user pool
Jeg tenker det er nais å ha muligheten til å overstyre slik at man kan bruke samme IDP og Role dersom man har flere domener som webapp kjører på. 

Man trenger en app monitor per domene, så dersom man ønsker å ha en på localhost (gitt MASSE verdi i tavler ved setup og testing) så må man opprette en egen Monitor. Da synes jeg det er nais å gjenbruke IDP og rolle, men kan godt dra det ut.

2023-10-23 13:29 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +   * Note: we will add a policy to PutEvents by cognito-identity service principal for unathenticated users.
Tja jeg vet ikke helt? 
Hvis man går for å bruke en IDP med authentiserte brukere og bruke den innebygde flyten så burde man være klar over at vi kun tillater rum:PutEvents ved uanthenticated users, men jeg tror brukstilfellet her er minimalt og at noen vil lese koden dersom de setter det opp uansett. 

Jeg kan ta det ut

2023-10-23 13:31 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +     * Attach policy here in stead of above as role is optional
Jeg mener policien egt hører til her: https://github.com/capralifecycle/liflig-cdk/blob/jlj/cw-rum-construct/src/webapp/app-monitor.ts#L164

Men siden vi også tillater å dytte inn en rolle som skal få den policien, måtte jeg gjøre det på en annen måte. 
Tenkte bare å skrive en liten docstring om hvorfor det er gjort sånn

2023-10-23 13:32 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +  sampleRate?: number
Jo, det risikerer vi, men dette må også settes i webapp repo. 
De færreste løsningene våre har mye trafikk, og det er nais å få full oversikt by default? Kan godt sette den til noe annet også. 
Jeg tror samtlige løsninger skal begynne med 100%

2023-10-25 11:21 UTC, stekern requested changes
This is a great addition to the library! Nice work 👏 

Functionally this seems to do the job. I have some specific comments for suggestions that can simplify the code and reduce footguns, as well a couple of minor nitpicks (which you're free to ignore if you disagree :D).

Some general input:
- Ideally the TSDoc should give consumers all the information they need to configure and use the construct correctly. I suggest we go through the TSDoc, add some more details and explanations where necessary, fix typos and try to avoid leaking unnecessary implementation details if any are present.
- Consider adding some TSDoc that describes how the construct properties are related to the properties that are set in the webapp using the CloudWatch RUM SDK where relevant. Maybe something along the lines of "The properties control the CloudWatch RUM functionality the web client is allowed to use. Enabling a property here needs to be accompanied by a corresponding change on the web client for it to actually take effect."
- We should do a quick review of the alarm descriptions and consider adding some more details that gives a bit more context and perhaps make them a bit more actionable.

(I've created a branch with some of my suggestions if you want some inspiration for how some of the suggestions may look in practice https://github.com/capralifecycle/liflig-cdk/commit/b94f02688b7c7c755499bf07398d3166903ff587)

2023-10-25 11:21 UTC, stekern commented on src/webapp/app-monitor.ts
> +    // These alarms are mandatory as costs should be mandator to monitor
I like that you've made this alarm mandatory to make it easier to catch avoid unexpected spikes :+1: Secure by design!

2023-10-25 11:21 UTC, stekern commented on src/webapp/index.ts
> +export { WebappMonitor } from "./app-monitor"
nit: Since the construct itself is called `WebappMonitor`, it may be more correct to name the file `monitor` instead of `app-monitor`

2023-10-25 11:34 UTC, stekern commented on src/__tests__/app-monitor.test.ts
> +  const snsTopicLogicalId = appMonitorStack.getLogicalId(
An alternative way of doing this:
```suggestion
  const snsTopicLogicalId = (snsTopic.node.defaultChild as CfnElement).logicalId
  // OR: const snsTopicLogicalId = (snsTopic.node.defaultChild as sns.CfnTopic).ref
```

2023-10-25 11:37 UTC, stekern commented on src/__tests__/app-monitor.test.ts
> +import { App, CfnElement, Stack } from "aws-cdk-lib"
Should we move the tests to `src/webapp/__tests__`?

2023-10-25 16:55 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +    const rumEventAlarm = new cloudwatch.Metric({
configureEventsAlarm to rewrite the alarm as suggested on line 235 gives the current error: 

```
There is already a Construct with name 'RumEventAlarm' in WebappMonitor [WebappMonitor]
```

2023-10-25 17:05 UTC, jakob-lj commented on src/webapp/app-monitor.ts
> +    const rumEventAlarm = new cloudwatch.Metric({
One could remove the construct using: 
````
this.tryRemoveChild("RumEventAlarm")
````

However, this seems a little wrong? Any other thoughts about how to do this? 

I'm thinking adding this override as props might be the better solution

2023-10-25 17:20 UTC, jakob-lj commented on src/__tests__/app-monitor.test.ts
> +  const snsTopicLogicalId = appMonitorStack.getLogicalId(
neither of these worked. 

I think it might be due to the scope? Not certain why it's necessary to create the stack "appMontiorStack" in tests, but thinking it has something to do with this?

2023-10-27 08:45 UTC, stekern reviewed
Good stuff!

I think we can simplify the tests a bit to make them easier to maintain and less brittle. I think the following should give us the sufficient coverage:
- A snapshot test using the default configuration for the construct
- A test that specifically checks that overriding the configuration for the mandatory alarm works (e.g., using `template.hasResourceProperties`), and that adding the optional alarm works.
  - When checking the optional alarm, it should be enough to just check that the number of CloudWatch alarm resources is 2 and that one of the alarms has `MetricName: "JsErrorCount"` and `Namespace: "AWS/RUM"`

There are some changes we can consider with regards to naming and documentation. 
You can see some of my proposed changes here: https://github.com/capralifecycle/liflig-cdk/commit/9ad2ebaa67b3792cf1f6e07ef861679fa9ac8009. Take a look and evaluate if there's anything useful there.

2023-10-27 08:51 UTC, stekern commented on src/__tests__/app-monitor.test.ts
> +  const snsTopicLogicalId = appMonitorStack.getLogicalId(
It's probably because they are CDK tokens. `appMonitorStack.getLogicalId(alarmActionTopic.node.defaultChild as CfnResource)` is another alternative that is a bit more concise that I think should work, but your approach is fine 👍

2023-10-27 10:29 UTC, stekern approved these changes
LGTM! Nice work.

Once you clean up the commits into a `feat` commit (to trigger a release) and get CI passing, this is ready to merge 🚀

2023-10-27 10:29 UTC, stekern commented on src/webapp/__tests__/monitor.test.ts
> +  const appMontiorStack = new Stack(app, "AppMonitorStack")
nit: typo
```suggestion
  const appMonitorStack = new Stack(app, "AppMonitorStack")
```

2023-10-27 10:29 UTC, stekern commented on src/webapp/monitor.ts
> +  telemetries: CwRumTelemetries
Should we simplify this by setting a default value here? If all consumers in practice are going to set this to `["http", "error", "performance"]`, the construct will be slightly easier to use.

2023-10-27 10:32 UTC, jakob-lj commented on src/webapp/monitor.ts
> +  telemetries: CwRumTelemetries
setting that as default yes

2023-10-27 11:13 UTC, merged

2023-10-27 11:19 UTC, calsCI commented
:tada: This PR is included in version 2.16.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/capralifecycle/liflig-cdk/releases/tag/v2.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: