Migrate from jenkins to GitHub actions
capralifecycle/liflig-cdk pull request #231
Opened 2024-02-07 13:16 UTC by joakimen

2024-02-07 13:21 UTC, joakimen commented on Jenkinsfile
> -      if (env.BRANCH_NAME ==~ /^(master|\d+\.(\d+|x)(\.x)?)$/) {
Didn't include support for releasing from non-trunk branches, such as referenced here.
We don't have any such branches today, nor any plans on supporting it afaik

2024-02-07 14:13 UTC, joakimen commented
Before adding these changes, we need to decide how to handle public NPM packages, marking as draft for now.

2024-02-09 08:51 UTC, joakimen commented
> Before adding these changes, we need to decide how to handle public NPM packages, marking as draft for now.

npm token strategy has been decided, and token has been added to workflow according to [the semrel guide](https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions)

2024-02-09 09:29 UTC, stekern requested changes
A couple of comments regarding job permissions, but otherwise looks good 🚀

2024-02-09 09:29 UTC, stekern commented on .github/workflows/ci.yml
> +      actions: read
Not required by the job

2024-02-09 09:29 UTC, stekern commented on .github/workflows/ci.yml
> +      id-token: write
Not required by the job

2024-02-09 09:29 UTC, stekern commented on .github/workflows/ci.yml
> +    permissions:
We likely also need `pull-requests: write` and `issues: write` permissions (https://github.com/semantic-release/semantic-release/issues/2469#issuecomment-1158013884)

2024-02-09 09:57 UTC, joakimen commented on .github/workflows/ci.yml
> +      id-token: write
https://github.com/capralifecycle/liflig-cdk/pull/231/commits/233b66cebbae498098c6309fde8a3f0c4def998d

2024-02-09 09:59 UTC, joakimen commented on .github/workflows/ci.yml
> +    permissions:
https://github.com/capralifecycle/liflig-cdk/pull/231/commits/a03e47063c838d082ca55497ac0e5869d4d842df 
https://github.com/capralifecycle/liflig-cdk/pull/231/commits/1ce9bccf8d9cde660781ddde7875b539cb2ab183

2024-02-09 09:59 UTC, joakimen commented on .github/workflows/ci.yml
> +      actions: read
https://github.com/capralifecycle/liflig-cdk/pull/231/commits/233b66cebbae498098c6309fde8a3f0c4def998d

2024-02-09 10:14 UTC, stekern approved these changes
LGTM!

I suggest we clean up the commit history a bit, and use a conventional commit type (e.g., `fix(ci): use github actions` or `feat(ci): use github actions`) that will trigger a release so we can verify that everything works as expected upon merge.

2024-02-09 10:14 UTC, stekern commented on .github/workflows/ci.yml
> +  build-and-deploy:
nit: build-and-release

2024-02-09 13:26 UTC, joakimen commented on .github/workflows/ci.yml
> +  build-and-deploy:
https://github.com/capralifecycle/liflig-cdk/pull/231/commits/c1fb632ba1de7fd498f36615a2d2b903c9f1740d#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR17

2024-02-09 13:30 UTC, merged