Add lambda invocation failure alarm
capralifecycle/liflig-cdk pull request #244
Opened 2024-05-10 15:13 UTC by krissrex

2024-05-10 15:15 UTC, krissrex commented on src/alarms/lambda-alarms.ts
> +      alarmDescription: `Invocation for '${this.lambdaFunctionName}' failed. ${props?.appendToAlarmDescription ?? ""}`,
Fjernet eksplisitt `alarmName` her. For å unngå collisions hvis man lager flere av samme construct or alarm.

2024-05-10 15:16 UTC, krissrex commented on src/alarms/lambda-alarms.ts
> +  lambdaFunctionName: string
Endret til å ta inn bare en lambda name som string i stedet for `lambda.Function`. Unngår imports her og lettere å skrive test-kode.

2024-05-10 15:17 UTC, krissrex commented on src/alarms/lambda-alarms.ts
> +  actions: cloudwatch.IAlarmAction[]
Den er en array, for i DTP har vi sendt samme alarm til fler actions, både Slack og OpsGenie.
Kan alternativt vært en enkelt `IAlarmAction` og så instansiert `LambdaAlarms` to ganger og lagd 2 `Alarms` i DTP, spesielt nå som jeg fjernet eksplisitt `alarmName`.

2024-05-15 13:27 UTC, joakimen requested changes
Bra tilskudd! Noen tilpasninger og forenklinger, så er det good :)

2024-05-15 13:27 UTC, joakimen commented on src/alarms/lambda-alarms.ts
> +  lambdaFunctionName: string
Har lurt litt på denne, og tror vi bør holde det til å sende inn selve funksjonen.
- Dersom vi senere introduserer andre alarmer/metrikker som ser på andre attributter i en lambda vil vi være nødt til å dytte ut en breaking change til alle konsumenter hvor vi endrer signaturen fra string (funksjonsnavn) til objekt (funksjon)
- Vi mister den eksplisitte CloudFormation-avhengigheten mellom metrikken og lambdaen. Det er ikke et problem i akkurat dette tilfellet, siden metrikken kan opprettes uavhengig, men det hadde vært kjekt å ha avhengigheten definert uansett

Så er ikke krise, men tror vi bør gjøre det for å ruste oss mot endringer

2024-05-15 13:27 UTC, joakimen commented on src/alarms/lambda-alarms.ts
> +      alarmDescription: `Invocation for '${this.lambdaFunctionName}' failed. ${props?.appendToAlarmDescription ?? ""}`,
Bra!

2024-05-15 13:27 UTC, joakimen commented on src/alarms/lambda-alarms.ts
> +export class LambdaAlarms extends constructs.Construct {
Kan ha en docstring som oppsummerer klassens ansvar, gjerne med notis tilsvarende service-alarms om at ingen alarmer opprettes før man kaller de forskjellige metodene

2025-07-29 07:23 UTC, merged